z1:
	gcc -std=c99 -pedantic -Wall -o build/z1 z1.c
z2:
	gcc -std=c99 -pedantic -Wall -o build/z2 z2.c
z3:
	gcc -std=c99 -pedantic -Wall -o build/z3 z3.c
z4:
	gcc -std=c99 -pedantic -Wall -o build/z4 z4.c
z6:
	gcc -std=c99 -pedantic -Wall -o build/z6 z6.c
z7:
	gcc -std=c99 -pedantic -Wall -o build/z7 z7.c

all: z1 z2 z3 z4 z6 z7
