/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "z1.h"

bool_t
xdr_osoba (XDR *xdrs, osoba *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->imie, 63))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nazwisko, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rok_urodzenia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_duza_liczba (XDR *xdrs, duza_liczba *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}
