/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _Z2_H_RPCGEN
#define _Z2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int sum_argument_len;
	u_int *sum_argument_val;
} sum_argument;

struct sum_wynik {
	bool_t wynik_jest_ok;
	union {
		u_int suma;
	} sum_wynik_u;
};
typedef struct sum_wynik sum_wynik;

#define SUM_PROGRAM 0x20002019
#define SUM_WERSJA_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM_OBLICZ 1
extern  sum_wynik * sum_oblicz_1(sum_argument *, CLIENT *);
extern  sum_wynik * sum_oblicz_1_svc(sum_argument *, struct svc_req *);
extern int sum_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM_OBLICZ 1
extern  sum_wynik * sum_oblicz_1();
extern  sum_wynik * sum_oblicz_1_svc();
extern int sum_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_argument (XDR *, sum_argument*);
extern  bool_t xdr_sum_wynik (XDR *, sum_wynik*);

#else /* K&R C */
extern bool_t xdr_sum_argument ();
extern bool_t xdr_sum_wynik ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_Z2_H_RPCGEN */
