/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "z2.h"

bool_t
xdr_sum_argument (XDR *xdrs, sum_argument *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->sum_argument_val, (u_int *) &objp->sum_argument_len, 100,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sum_wynik (XDR *xdrs, sum_wynik *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->wynik_jest_ok))
		 return FALSE;
	switch (objp->wynik_jest_ok) {
	case TRUE:
		 if (!xdr_u_int (xdrs, &objp->sum_wynik_u.suma))
			 return FALSE;
		break;
	case FALSE:
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
