z5:
	gcc -std=c99 -pedantic -Wall -o build/z5 z5.c
z7:
	gcc -std=c99 -pedantic -Wall -o build/z7 z7.c
z9-client:
	gcc -std=c99 -pedantic -Wall -o build/z9-client z9-client.c
z9-server:
	gcc -std=c99 -pedantic -Wall -o build/z9-server z9-server.c

all: z5 z7 z9-client z9-server
